// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/project_handler.proto

package project_creator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateProjectRequest struct {
	Email                 string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Xid                   string   `protobuf:"bytes,2,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                 string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Projectleader         string   `protobuf:"bytes,4,opt,name=projectleader,proto3" json:"projectleader,omitempty"`
	Percentdone           int32    `protobuf:"varint,5,opt,name=percentdone,proto3" json:"percentdone,omitempty"`
	Groupsize             int32    `protobuf:"varint,6,opt,name=groupsize,proto3" json:"groupsize,omitempty"`
	Isprivate             bool     `protobuf:"varint,7,opt,name=isprivate,proto3" json:"isprivate,omitempty"`
	Tags                  []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Deadline              string   `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Calendarid            string   `protobuf:"bytes,10,opt,name=calendarid,proto3" json:"calendarid,omitempty"`
	Description           string   `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Done                  bool     `protobuf:"varint,12,opt,name=done,proto3" json:"done,omitempty"`
	Joinrequests          []string `protobuf:"bytes,13,rep,name=joinrequests,proto3" json:"joinrequests,omitempty"`
	Memberslist           []string `protobuf:"bytes,14,rep,name=memberslist,proto3" json:"memberslist,omitempty"`
	Milestones            []string `protobuf:"bytes,15,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Pinnedannouncements   []string `protobuf:"bytes,16,rep,name=pinnedannouncements,proto3" json:"pinnedannouncements,omitempty"`
	Unpinnedannouncements []string `protobuf:"bytes,17,rep,name=unpinnedannouncements,proto3" json:"unpinnedannouncements,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{0}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateProjectRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *CreateProjectRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateProjectRequest) GetProjectleader() string {
	if m != nil {
		return m.Projectleader
	}
	return ""
}

func (m *CreateProjectRequest) GetPercentdone() int32 {
	if m != nil {
		return m.Percentdone
	}
	return 0
}

func (m *CreateProjectRequest) GetGroupsize() int32 {
	if m != nil {
		return m.Groupsize
	}
	return 0
}

func (m *CreateProjectRequest) GetIsprivate() bool {
	if m != nil {
		return m.Isprivate
	}
	return false
}

func (m *CreateProjectRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateProjectRequest) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *CreateProjectRequest) GetCalendarid() string {
	if m != nil {
		return m.Calendarid
	}
	return ""
}

func (m *CreateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProjectRequest) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *CreateProjectRequest) GetJoinrequests() []string {
	if m != nil {
		return m.Joinrequests
	}
	return nil
}

func (m *CreateProjectRequest) GetMemberslist() []string {
	if m != nil {
		return m.Memberslist
	}
	return nil
}

func (m *CreateProjectRequest) GetMilestones() []string {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *CreateProjectRequest) GetPinnedannouncements() []string {
	if m != nil {
		return m.Pinnedannouncements
	}
	return nil
}

func (m *CreateProjectRequest) GetUnpinnedannouncements() []string {
	if m != nil {
		return m.Unpinnedannouncements
	}
	return nil
}

type CreateProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{1}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetAllProjectsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProjectsRequest) Reset()         { *m = GetAllProjectsRequest{} }
func (m *GetAllProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProjectsRequest) ProtoMessage()    {}
func (*GetAllProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{2}
}

func (m *GetAllProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProjectsRequest.Unmarshal(m, b)
}
func (m *GetAllProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProjectsRequest.Merge(m, src)
}
func (m *GetAllProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProjectsRequest.Size(m)
}
func (m *GetAllProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProjectsRequest proto.InternalMessageInfo

func (m *GetAllProjectsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Projects struct {
	Xid                   string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                 string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Projectleader         string   `protobuf:"bytes,3,opt,name=projectleader,proto3" json:"projectleader,omitempty"`
	Percentdone           int32    `protobuf:"varint,4,opt,name=percentdone,proto3" json:"percentdone,omitempty"`
	Groupsize             int32    `protobuf:"varint,5,opt,name=groupsize,proto3" json:"groupsize,omitempty"`
	Isprivate             bool     `protobuf:"varint,6,opt,name=isprivate,proto3" json:"isprivate,omitempty"`
	Tags                  []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Deadline              string   `protobuf:"bytes,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Calendarid            string   `protobuf:"bytes,9,opt,name=calendarid,proto3" json:"calendarid,omitempty"`
	Description           string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Done                  bool     `protobuf:"varint,11,opt,name=done,proto3" json:"done,omitempty"`
	Joinrequests          []string `protobuf:"bytes,12,rep,name=joinrequests,proto3" json:"joinrequests,omitempty"`
	Memberslist           []string `protobuf:"bytes,13,rep,name=memberslist,proto3" json:"memberslist,omitempty"`
	Milestones            []string `protobuf:"bytes,14,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Pinnedannouncements   []string `protobuf:"bytes,15,rep,name=pinnedannouncements,proto3" json:"pinnedannouncements,omitempty"`
	Unpinnedannouncements []string `protobuf:"bytes,16,rep,name=unpinnedannouncements,proto3" json:"unpinnedannouncements,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{3}
}

func (m *Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projects.Unmarshal(m, b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
}
func (m *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(m, src)
}
func (m *Projects) XXX_Size() int {
	return xxx_messageInfo_Projects.Size(m)
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *Projects) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Projects) GetProjectleader() string {
	if m != nil {
		return m.Projectleader
	}
	return ""
}

func (m *Projects) GetPercentdone() int32 {
	if m != nil {
		return m.Percentdone
	}
	return 0
}

func (m *Projects) GetGroupsize() int32 {
	if m != nil {
		return m.Groupsize
	}
	return 0
}

func (m *Projects) GetIsprivate() bool {
	if m != nil {
		return m.Isprivate
	}
	return false
}

func (m *Projects) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Projects) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *Projects) GetCalendarid() string {
	if m != nil {
		return m.Calendarid
	}
	return ""
}

func (m *Projects) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Projects) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Projects) GetJoinrequests() []string {
	if m != nil {
		return m.Joinrequests
	}
	return nil
}

func (m *Projects) GetMemberslist() []string {
	if m != nil {
		return m.Memberslist
	}
	return nil
}

func (m *Projects) GetMilestones() []string {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *Projects) GetPinnedannouncements() []string {
	if m != nil {
		return m.Pinnedannouncements
	}
	return nil
}

func (m *Projects) GetUnpinnedannouncements() []string {
	if m != nil {
		return m.Unpinnedannouncements
	}
	return nil
}

type GetAllProjectsResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Projects             []*Projects `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllProjectsResponse) Reset()         { *m = GetAllProjectsResponse{} }
func (m *GetAllProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllProjectsResponse) ProtoMessage()    {}
func (*GetAllProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{4}
}

func (m *GetAllProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProjectsResponse.Unmarshal(m, b)
}
func (m *GetAllProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProjectsResponse.Merge(m, src)
}
func (m *GetAllProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllProjectsResponse.Size(m)
}
func (m *GetAllProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProjectsResponse proto.InternalMessageInfo

func (m *GetAllProjectsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAllProjectsResponse) GetProjects() []*Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetProjectsRequest struct {
	Xid                  []string `protobuf:"bytes,1,rep,name=xid,proto3" json:"xid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{5}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

func (m *GetProjectsRequest) GetXid() []string {
	if m != nil {
		return m.Xid
	}
	return nil
}

type GetProjectsResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Projects             []*Projects `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{6}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProjectsResponse) GetProjects() []*Projects {
	if m != nil {
		return m.Projects
	}
	return nil
}

type UpdateProjectsRequest struct {
	Xid                   string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                 string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Projectleader         string   `protobuf:"bytes,3,opt,name=projectleader,proto3" json:"projectleader,omitempty"`
	Percentdone           int32    `protobuf:"varint,4,opt,name=percentdone,proto3" json:"percentdone,omitempty"`
	Groupsize             int32    `protobuf:"varint,5,opt,name=groupsize,proto3" json:"groupsize,omitempty"`
	Isprivate             bool     `protobuf:"varint,6,opt,name=isprivate,proto3" json:"isprivate,omitempty"`
	Tags                  []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Deadline              string   `protobuf:"bytes,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Calendarid            string   `protobuf:"bytes,9,opt,name=calendarid,proto3" json:"calendarid,omitempty"`
	Description           string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Done                  bool     `protobuf:"varint,11,opt,name=done,proto3" json:"done,omitempty"`
	Joinrequests          []string `protobuf:"bytes,12,rep,name=joinrequests,proto3" json:"joinrequests,omitempty"`
	Memberslist           []string `protobuf:"bytes,13,rep,name=memberslist,proto3" json:"memberslist,omitempty"`
	Milestones            []string `protobuf:"bytes,14,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Pinnedannouncements   []string `protobuf:"bytes,15,rep,name=pinnedannouncements,proto3" json:"pinnedannouncements,omitempty"`
	Unpinnedannouncements []string `protobuf:"bytes,16,rep,name=unpinnedannouncements,proto3" json:"unpinnedannouncements,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UpdateProjectsRequest) Reset()         { *m = UpdateProjectsRequest{} }
func (m *UpdateProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectsRequest) ProtoMessage()    {}
func (*UpdateProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{7}
}

func (m *UpdateProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectsRequest.Unmarshal(m, b)
}
func (m *UpdateProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectsRequest.Merge(m, src)
}
func (m *UpdateProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectsRequest.Size(m)
}
func (m *UpdateProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectsRequest proto.InternalMessageInfo

func (m *UpdateProjectsRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *UpdateProjectsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateProjectsRequest) GetProjectleader() string {
	if m != nil {
		return m.Projectleader
	}
	return ""
}

func (m *UpdateProjectsRequest) GetPercentdone() int32 {
	if m != nil {
		return m.Percentdone
	}
	return 0
}

func (m *UpdateProjectsRequest) GetGroupsize() int32 {
	if m != nil {
		return m.Groupsize
	}
	return 0
}

func (m *UpdateProjectsRequest) GetIsprivate() bool {
	if m != nil {
		return m.Isprivate
	}
	return false
}

func (m *UpdateProjectsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UpdateProjectsRequest) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *UpdateProjectsRequest) GetCalendarid() string {
	if m != nil {
		return m.Calendarid
	}
	return ""
}

func (m *UpdateProjectsRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProjectsRequest) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *UpdateProjectsRequest) GetJoinrequests() []string {
	if m != nil {
		return m.Joinrequests
	}
	return nil
}

func (m *UpdateProjectsRequest) GetMemberslist() []string {
	if m != nil {
		return m.Memberslist
	}
	return nil
}

func (m *UpdateProjectsRequest) GetMilestones() []string {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *UpdateProjectsRequest) GetPinnedannouncements() []string {
	if m != nil {
		return m.Pinnedannouncements
	}
	return nil
}

func (m *UpdateProjectsRequest) GetUnpinnedannouncements() []string {
	if m != nil {
		return m.Unpinnedannouncements
	}
	return nil
}

type UpdateProjectsResponse struct {
	Success               bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Xid                   string   `protobuf:"bytes,2,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                 string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Projectleader         string   `protobuf:"bytes,4,opt,name=projectleader,proto3" json:"projectleader,omitempty"`
	Percentdone           int32    `protobuf:"varint,5,opt,name=percentdone,proto3" json:"percentdone,omitempty"`
	Groupsize             int32    `protobuf:"varint,6,opt,name=groupsize,proto3" json:"groupsize,omitempty"`
	Isprivate             bool     `protobuf:"varint,7,opt,name=isprivate,proto3" json:"isprivate,omitempty"`
	Tags                  []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Deadline              string   `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Calendarid            string   `protobuf:"bytes,10,opt,name=calendarid,proto3" json:"calendarid,omitempty"`
	Description           string   `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Done                  bool     `protobuf:"varint,12,opt,name=done,proto3" json:"done,omitempty"`
	Joinrequests          []string `protobuf:"bytes,13,rep,name=joinrequests,proto3" json:"joinrequests,omitempty"`
	Memberslist           []string `protobuf:"bytes,14,rep,name=memberslist,proto3" json:"memberslist,omitempty"`
	Milestones            []string `protobuf:"bytes,15,rep,name=milestones,proto3" json:"milestones,omitempty"`
	Pinnedannouncements   []string `protobuf:"bytes,16,rep,name=pinnedannouncements,proto3" json:"pinnedannouncements,omitempty"`
	Unpinnedannouncements []string `protobuf:"bytes,17,rep,name=unpinnedannouncements,proto3" json:"unpinnedannouncements,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UpdateProjectsResponse) Reset()         { *m = UpdateProjectsResponse{} }
func (m *UpdateProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectsResponse) ProtoMessage()    {}
func (*UpdateProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{8}
}

func (m *UpdateProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectsResponse.Unmarshal(m, b)
}
func (m *UpdateProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectsResponse.Merge(m, src)
}
func (m *UpdateProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectsResponse.Size(m)
}
func (m *UpdateProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectsResponse proto.InternalMessageInfo

func (m *UpdateProjectsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateProjectsResponse) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *UpdateProjectsResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateProjectsResponse) GetProjectleader() string {
	if m != nil {
		return m.Projectleader
	}
	return ""
}

func (m *UpdateProjectsResponse) GetPercentdone() int32 {
	if m != nil {
		return m.Percentdone
	}
	return 0
}

func (m *UpdateProjectsResponse) GetGroupsize() int32 {
	if m != nil {
		return m.Groupsize
	}
	return 0
}

func (m *UpdateProjectsResponse) GetIsprivate() bool {
	if m != nil {
		return m.Isprivate
	}
	return false
}

func (m *UpdateProjectsResponse) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UpdateProjectsResponse) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *UpdateProjectsResponse) GetCalendarid() string {
	if m != nil {
		return m.Calendarid
	}
	return ""
}

func (m *UpdateProjectsResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProjectsResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *UpdateProjectsResponse) GetJoinrequests() []string {
	if m != nil {
		return m.Joinrequests
	}
	return nil
}

func (m *UpdateProjectsResponse) GetMemberslist() []string {
	if m != nil {
		return m.Memberslist
	}
	return nil
}

func (m *UpdateProjectsResponse) GetMilestones() []string {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *UpdateProjectsResponse) GetPinnedannouncements() []string {
	if m != nil {
		return m.Pinnedannouncements
	}
	return nil
}

func (m *UpdateProjectsResponse) GetUnpinnedannouncements() []string {
	if m != nil {
		return m.Unpinnedannouncements
	}
	return nil
}

type JoinProjectRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinProjectRequest) Reset()         { *m = JoinProjectRequest{} }
func (m *JoinProjectRequest) String() string { return proto.CompactTextString(m) }
func (*JoinProjectRequest) ProtoMessage()    {}
func (*JoinProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{9}
}

func (m *JoinProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinProjectRequest.Unmarshal(m, b)
}
func (m *JoinProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinProjectRequest.Marshal(b, m, deterministic)
}
func (m *JoinProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinProjectRequest.Merge(m, src)
}
func (m *JoinProjectRequest) XXX_Size() int {
	return xxx_messageInfo_JoinProjectRequest.Size(m)
}
func (m *JoinProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinProjectRequest proto.InternalMessageInfo

func (m *JoinProjectRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *JoinProjectRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type JoinProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinProjectResponse) Reset()         { *m = JoinProjectResponse{} }
func (m *JoinProjectResponse) String() string { return proto.CompactTextString(m) }
func (*JoinProjectResponse) ProtoMessage()    {}
func (*JoinProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b74e335e85f3fb3, []int{10}
}

func (m *JoinProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinProjectResponse.Unmarshal(m, b)
}
func (m *JoinProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinProjectResponse.Marshal(b, m, deterministic)
}
func (m *JoinProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinProjectResponse.Merge(m, src)
}
func (m *JoinProjectResponse) XXX_Size() int {
	return xxx_messageInfo_JoinProjectResponse.Size(m)
}
func (m *JoinProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinProjectResponse proto.InternalMessageInfo

func (m *JoinProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateProjectRequest)(nil), "project_creator.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "project_creator.CreateProjectResponse")
	proto.RegisterType((*GetAllProjectsRequest)(nil), "project_creator.GetAllProjectsRequest")
	proto.RegisterType((*Projects)(nil), "project_creator.Projects")
	proto.RegisterType((*GetAllProjectsResponse)(nil), "project_creator.GetAllProjectsResponse")
	proto.RegisterType((*GetProjectsRequest)(nil), "project_creator.GetProjectsRequest")
	proto.RegisterType((*GetProjectsResponse)(nil), "project_creator.GetProjectsResponse")
	proto.RegisterType((*UpdateProjectsRequest)(nil), "project_creator.UpdateProjectsRequest")
	proto.RegisterType((*UpdateProjectsResponse)(nil), "project_creator.UpdateProjectsResponse")
	proto.RegisterType((*JoinProjectRequest)(nil), "project_creator.JoinProjectRequest")
	proto.RegisterType((*JoinProjectResponse)(nil), "project_creator.JoinProjectResponse")
}

func init() { proto.RegisterFile("protos/project_handler.proto", fileDescriptor_4b74e335e85f3fb3) }

var fileDescriptor_4b74e335e85f3fb3 = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x97, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xc7, 0x95, 0xc4, 0x69, 0x93, 0x93, 0xaf, 0x76, 0xd2, 0xf4, 0x4e, 0xa3, 0xea, 0x2a, 0xf2,
	0xed, 0x2d, 0x11, 0x12, 0x0d, 0x14, 0xd8, 0x20, 0x36, 0x55, 0x17, 0x15, 0xac, 0xaa, 0x48, 0xac,
	0x91, 0x6b, 0x1f, 0xc2, 0x54, 0xce, 0x8c, 0xeb, 0x99, 0x20, 0x3e, 0xc4, 0x86, 0x25, 0x5b, 0x16,
	0xbc, 0x04, 0x2b, 0x5e, 0x85, 0x57, 0xe0, 0x09, 0x78, 0x02, 0xe4, 0xb1, 0x93, 0x3a, 0xce, 0xd4,
	0xae, 0x90, 0x58, 0xb5, 0x3b, 0xcf, 0x99, 0xff, 0xcc, 0x39, 0x67, 0xf2, 0x9b, 0x73, 0x26, 0xb0,
	0x1b, 0x84, 0x42, 0x09, 0x39, 0x0a, 0x42, 0x71, 0x8e, 0xae, 0x7a, 0xf9, 0xda, 0xe1, 0x9e, 0x8f,
	0xe1, 0x81, 0x36, 0x93, 0xce, 0xdc, 0xec, 0x86, 0xe8, 0x28, 0x11, 0xf6, 0x77, 0x27, 0x42, 0x4c,
	0x7c, 0x1c, 0x39, 0x01, 0x1b, 0x39, 0x9c, 0x0b, 0xe5, 0x28, 0x26, 0xb8, 0x8c, 0xe5, 0xf6, 0x37,
	0x0b, 0xb6, 0x8e, 0x23, 0x25, 0x9e, 0xc6, 0xeb, 0xc6, 0x78, 0x31, 0x43, 0xa9, 0xc8, 0x16, 0x54,
	0x71, 0xea, 0x30, 0x9f, 0x96, 0x06, 0xa5, 0x61, 0x7d, 0x1c, 0x0f, 0xc8, 0x06, 0x54, 0xde, 0x32,
	0x8f, 0x96, 0xb5, 0x2d, 0xfa, 0x8c, 0x74, 0x8a, 0x29, 0x1f, 0x69, 0x25, 0xd6, 0xe9, 0x01, 0xd9,
	0x83, 0x56, 0x12, 0x87, 0x8f, 0x8e, 0x87, 0x21, 0xb5, 0xf4, 0xec, 0xb2, 0x91, 0x0c, 0xa0, 0x11,
	0x60, 0xe8, 0x22, 0x57, 0x9e, 0xe0, 0x48, 0xab, 0x83, 0xd2, 0xb0, 0x3a, 0x4e, 0x9b, 0xc8, 0x2e,
	0xd4, 0x27, 0xa1, 0x98, 0x05, 0x92, 0xbd, 0x47, 0xba, 0xa6, 0xe7, 0x2f, 0x0d, 0xd1, 0x2c, 0x93,
	0x41, 0xc8, 0xde, 0x38, 0x0a, 0xe9, 0xfa, 0xa0, 0x34, 0xac, 0x8d, 0x2f, 0x0d, 0x84, 0x80, 0xa5,
	0x9c, 0x89, 0xa4, 0xb5, 0x41, 0x65, 0x58, 0x1f, 0xeb, 0x6f, 0xd2, 0x87, 0x9a, 0x87, 0x8e, 0xe7,
	0x33, 0x8e, 0xb4, 0xae, 0x43, 0x5a, 0x8c, 0xc9, 0xbf, 0x00, 0xae, 0xe3, 0x23, 0xf7, 0x9c, 0x90,
	0x79, 0x14, 0xf4, 0x6c, 0xca, 0x12, 0x45, 0xeb, 0xa1, 0x74, 0x43, 0x16, 0x44, 0x07, 0x48, 0x1b,
	0x5a, 0x90, 0x36, 0x45, 0x1e, 0x75, 0x22, 0x4d, 0x1d, 0x8a, 0xfe, 0x26, 0x36, 0x34, 0xcf, 0x05,
	0xe3, 0x61, 0x7c, 0xac, 0x92, 0xb6, 0x74, 0x34, 0x4b, 0xb6, 0x68, 0xe7, 0x29, 0x4e, 0xcf, 0x30,
	0x94, 0x3e, 0x93, 0x8a, 0xb6, 0xb5, 0x24, 0x6d, 0x8a, 0x62, 0x9b, 0x32, 0x1f, 0xa5, 0x12, 0x1c,
	0x25, 0xed, 0x68, 0x41, 0xca, 0x42, 0xee, 0x43, 0x37, 0x60, 0x9c, 0xa3, 0x17, 0xfd, 0xc2, 0x33,
	0xee, 0xe2, 0x14, 0xb9, 0x92, 0x74, 0x43, 0x0b, 0x4d, 0x53, 0xe4, 0x11, 0xf4, 0x66, 0xdc, 0xb4,
	0x66, 0x53, 0xaf, 0x31, 0x4f, 0xda, 0x0f, 0xa0, 0x97, 0xa1, 0x45, 0x06, 0x82, 0x4b, 0x24, 0x14,
	0xd6, 0xe5, 0xcc, 0x75, 0x51, 0x4a, 0x0d, 0x4c, 0x6d, 0x3c, 0x1f, 0xda, 0xf7, 0xa0, 0x77, 0x82,
	0xea, 0xc8, 0xf7, 0x93, 0x25, 0x32, 0x97, 0x30, 0xfb, 0xb3, 0x05, 0xb5, 0xb9, 0x72, 0x8e, 0x5b,
	0xc9, 0x80, 0x5b, 0x39, 0x17, 0xb7, 0xca, 0x35, 0x70, 0xb3, 0x0a, 0x70, 0xab, 0xe6, 0xe2, 0xb6,
	0x76, 0x15, 0x6e, 0xeb, 0x57, 0xe0, 0x56, 0xcb, 0xc5, 0xad, 0x5e, 0x84, 0x1b, 0x5c, 0x8d, 0x5b,
	0x23, 0x07, 0xb7, 0x66, 0x31, 0x6e, 0xad, 0x22, 0xdc, 0xda, 0xd7, 0xc5, 0xad, 0xf3, 0x07, 0xb8,
	0x6d, 0xe4, 0xe1, 0xc6, 0x60, 0x3b, 0xcb, 0x4e, 0x11, 0x6f, 0xe4, 0x31, 0xd4, 0x92, 0x9f, 0x5d,
	0xd2, 0xf2, 0xa0, 0x32, 0x6c, 0x1c, 0xee, 0x1c, 0x64, 0x6a, 0xe2, 0xc1, 0x62, 0xbb, 0x85, 0xd4,
	0xde, 0x07, 0x72, 0x82, 0x2a, 0xcb, 0xe8, 0x02, 0xc0, 0x4a, 0x02, 0xa0, 0xfd, 0x0a, 0xba, 0x4b,
	0xba, 0xbf, 0x15, 0xcf, 0x57, 0x0b, 0x7a, 0x2f, 0x02, 0xef, 0xf2, 0xaa, 0xad, 0xc6, 0x74, 0x7b,
	0x29, 0x6e, 0xe4, 0xa5, 0xf8, 0x6e, 0xc1, 0x76, 0x96, 0x8c, 0x42, 0x0a, 0x6f, 0x1b, 0xf7, 0xcd,
	0x6e, 0xdc, 0x4f, 0x81, 0x3c, 0x17, 0x8c, 0x67, 0x1e, 0x79, 0xc6, 0x52, 0x12, 0x37, 0xe5, 0x72,
	0xba, 0x29, 0x8f, 0xa0, 0xbb, 0xb4, 0xba, 0x08, 0xb7, 0xc3, 0x5f, 0x16, 0x6c, 0x26, 0xea, 0xe3,
	0xb8, 0xc6, 0x1d, 0x9d, 0x3e, 0x23, 0xef, 0xa0, 0xb5, 0xf4, 0x7a, 0x20, 0xff, 0xaf, 0x54, 0x42,
	0xd3, 0x5b, 0xb4, 0xbf, 0x5f, 0x24, 0x8b, 0xe3, 0xb1, 0x77, 0x3e, 0xfd, 0xf8, 0xf9, 0xa5, 0xdc,
	0xb5, 0xdb, 0x23, 0xad, 0xc3, 0x64, 0xd5, 0x93, 0xd2, 0x5d, 0xf2, 0x11, 0xda, 0xcb, 0x9d, 0x84,
	0xac, 0x6e, 0x6a, 0x7c, 0xa6, 0xf4, 0xef, 0x14, 0xea, 0x12, 0xef, 0x7d, 0xed, 0x7d, 0xcb, 0xee,
	0x8c, 0x26, 0xa8, 0x1c, 0xdf, 0x9f, 0x97, 0xf2, 0xc8, 0xfd, 0x05, 0x34, 0x52, 0x5d, 0x83, 0xfc,
	0x67, 0xda, 0x33, 0xeb, 0x78, 0x2f, 0x5f, 0x94, 0x78, 0xfd, 0x47, 0x7b, 0xdd, 0xb4, 0x9b, 0x91,
	0xd7, 0xb4, 0xcb, 0x0f, 0xd0, 0x5a, 0xaa, 0x12, 0x86, 0x84, 0x8d, 0xfd, 0xc5, 0x90, 0xb0, 0xb9,
	0xda, 0xa4, 0x8e, 0x7b, 0xa6, 0x05, 0xa9, 0xe3, 0x96, 0xd0, 0x4c, 0x01, 0x63, 0x4a, 0x78, 0x95,
	0x46, 0x43, 0xc2, 0x06, 0xe8, 0x6c, 0xaa, 0xbd, 0x12, 0xbb, 0x35, 0x8a, 0xae, 0x62, 0x2a, 0xe3,
	0xb3, 0x35, 0xfd, 0x97, 0xe6, 0xe1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0xac, 0x94, 0xa1,
	0x21, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectCreatorAPIClient is the client API for ProjectCreatorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectCreatorAPIClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetAllProjects(ctx context.Context, in *GetAllProjectsRequest, opts ...grpc.CallOption) (*GetAllProjectsResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectsRequest, opts ...grpc.CallOption) (*UpdateProjectsResponse, error)
	JoinProjects(ctx context.Context, in *JoinProjectRequest, opts ...grpc.CallOption) (*JoinProjectResponse, error)
}

type projectCreatorAPIClient struct {
	cc *grpc.ClientConn
}

func NewProjectCreatorAPIClient(cc *grpc.ClientConn) ProjectCreatorAPIClient {
	return &projectCreatorAPIClient{cc}
}

func (c *projectCreatorAPIClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/project_creator.ProjectCreatorAPI/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectCreatorAPIClient) GetAllProjects(ctx context.Context, in *GetAllProjectsRequest, opts ...grpc.CallOption) (*GetAllProjectsResponse, error) {
	out := new(GetAllProjectsResponse)
	err := c.cc.Invoke(ctx, "/project_creator.ProjectCreatorAPI/GetAllProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectCreatorAPIClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/project_creator.ProjectCreatorAPI/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectCreatorAPIClient) UpdateProject(ctx context.Context, in *UpdateProjectsRequest, opts ...grpc.CallOption) (*UpdateProjectsResponse, error) {
	out := new(UpdateProjectsResponse)
	err := c.cc.Invoke(ctx, "/project_creator.ProjectCreatorAPI/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectCreatorAPIClient) JoinProjects(ctx context.Context, in *JoinProjectRequest, opts ...grpc.CallOption) (*JoinProjectResponse, error) {
	out := new(JoinProjectResponse)
	err := c.cc.Invoke(ctx, "/project_creator.ProjectCreatorAPI/JoinProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectCreatorAPIServer is the server API for ProjectCreatorAPI service.
type ProjectCreatorAPIServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetAllProjects(context.Context, *GetAllProjectsRequest) (*GetAllProjectsResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	UpdateProject(context.Context, *UpdateProjectsRequest) (*UpdateProjectsResponse, error)
	JoinProjects(context.Context, *JoinProjectRequest) (*JoinProjectResponse, error)
}

func RegisterProjectCreatorAPIServer(s *grpc.Server, srv ProjectCreatorAPIServer) {
	s.RegisterService(&_ProjectCreatorAPI_serviceDesc, srv)
}

func _ProjectCreatorAPI_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectCreatorAPIServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_creator.ProjectCreatorAPI/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectCreatorAPIServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectCreatorAPI_GetAllProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectCreatorAPIServer).GetAllProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_creator.ProjectCreatorAPI/GetAllProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectCreatorAPIServer).GetAllProjects(ctx, req.(*GetAllProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectCreatorAPI_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectCreatorAPIServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_creator.ProjectCreatorAPI/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectCreatorAPIServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectCreatorAPI_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectCreatorAPIServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_creator.ProjectCreatorAPI/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectCreatorAPIServer).UpdateProject(ctx, req.(*UpdateProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectCreatorAPI_JoinProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectCreatorAPIServer).JoinProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_creator.ProjectCreatorAPI/JoinProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectCreatorAPIServer).JoinProjects(ctx, req.(*JoinProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectCreatorAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "project_creator.ProjectCreatorAPI",
	HandlerType: (*ProjectCreatorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ProjectCreatorAPI_CreateProject_Handler,
		},
		{
			MethodName: "GetAllProjects",
			Handler:    _ProjectCreatorAPI_GetAllProjects_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _ProjectCreatorAPI_GetProjects_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectCreatorAPI_UpdateProject_Handler,
		},
		{
			MethodName: "JoinProjects",
			Handler:    _ProjectCreatorAPI_JoinProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/project_handler.proto",
}
